[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1

fs_permissions = [{ access = "read", path = "./script/deployParameters/"}]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-53/=lib/openzeppelin-contracts-53/",
    "forge-std/=lib/forge-std/src/",
    "base64-sol/=lib/base64/",
    "@uniswap/lib/contracts/=lib/uniswap-lib/contracts/",
    "solmate/=lib/solmate/"
]

[rpc_endpoints]
mainnet = "https://mainnet.evm.nodes.onflow.org"
testnet = "https://testnet.evm.nodes.onflow.org"
